# Generated by Django 3.1.5 on 2022-07-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of Hotel')),
                ('accommadate', models.CharField(max_length=120, verbose_name='accommadate')),
                ('confernce', models.CharField(max_length=120, verbose_name='conference')),
                ('contact_name', models.CharField(max_length=120, verbose_name='contact name')),
                ('contact_mobile', models.CharField(max_length=120, verbose_name='contact mobile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('quantity', models.IntegerField(blank=True, max_length=120, verbose_name='quantity')),
                ('amount', models.IntegerField(max_length=120, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('descriprion', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Ticketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of Company')),
                ('contact', models.IntegerField(max_length=120, verbose_name='Contact Person')),
                ('mobile', models.IntegerField(max_length=120, verbose_name='Telephone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('services', models.CharField(max_length=120, verbose_name='services')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of Company')),
                ('contact', models.IntegerField(max_length=120, verbose_name='Contact Person')),
                ('mobile', models.IntegerField(max_length=120, verbose_name='Telephone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('services', models.CharField(max_length=120, verbose_name='services')),
            ],
        ),
    ]
