# Generated by Django 3.1.5 on 2022-07-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('quantity', models.IntegerField(blank=True, max_length=120, verbose_name='quantity')),
                ('amount', models.IntegerField(max_length=120, verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('descriprion', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
