# Generated by Django 3.1.5 on 2022-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220727_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='added', max_length=120, verbose_name='Add status'),
            preserve_default=False,
        ),
    ]
