# Generated by Django 3.1.5 on 2022-07-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(max_length=120, verbose_name='status'),
        ),
    ]
