# Generated by Django 3.1.5 on 2022-07-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20220727_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=120, null=True, verbose_name='quantity'),
        ),
    ]
