# Generated by Django 3.1.5 on 2022-07-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20220727_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='amount',
            field=models.IntegerField(blank=True, max_length=120, verbose_name='Amount'),
        ),
    ]
