# Generated by Django 3.1.5 on 2022-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20220729_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='amount',
            field=models.IntegerField(blank=True, max_length=120, null=True, verbose_name='Amount'),
        ),
    ]
