# Generated by Django 3.1.5 on 2022-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20220801_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketing',
            name='time',
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='name',
            field=models.CharField(default='opiman', max_length=120, verbose_name='Name of Company'),
        ),
    ]
