# Generated by Django 3.1.5 on 2022-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20220801_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=120, verbose_name='Name of Company')),
                ('quantity', models.IntegerField(verbose_name='Given Out')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name of Company'),
        ),
        migrations.CreateModel(
            name='Iec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquisition', models.CharField(default='2016', max_length=120, verbose_name='Acquisition Date')),
                ('accession_number', models.CharField(blank=True, max_length=120, null=True, verbose_name='Accession Number ')),
                ('author', models.CharField(max_length=120, verbose_name='Author')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('publisher', models.CharField(max_length=120, verbose_name='Publisher')),
                ('publication_place', models.CharField(default='Nairobi, Kenya', max_length=120, verbose_name='Publication Place')),
                ('publication_date', models.CharField(max_length=120, verbose_name='Publication Date')),
                ('store', models.IntegerField(verbose_name='store')),
                ('out', models.ManyToManyField(to='activities.Out')),
            ],
        ),
    ]
