# Generated by Django 3.1.5 on 2022-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20220801_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iec',
            name='date_acquisition',
            field=models.CharField(default='date', max_length=120, verbose_name='Acquisition Date'),
        ),
    ]
