# Generated by Django 3.1.5 on 2022-08-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_iec_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iec',
        ),
    ]
